In [1]:
import numpy as np


In [2]:
#tạo mảng
a = np.array([1,2,3])

#in mảng 
print(a)

#in ra 1 phần tử
ele = a[1]
print(ele)

[1 2 3]
2


In [3]:
#tạo mảng 2 chiều

In [4]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("matrix: ")
print(matrix)

matrix: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#in một phần tử 
# In một phần tử
element = matrix[1, 2]
print(element)

6


In [6]:
# Cách tạo mảng
# Tạo mảng toàn là số 0
a = np.zeros(5)
print(a)

# Tạo mảng toàn là số 1
a = np.ones(5)
print(a)

# Tạo mảng
a = np.empty(5)
print(a)

# Tạo mảng từ 0 đến 100
a = np.arange(100)
print(a)

# Tạo mảng gồm các phần tử với khoảng cách đều nhau
a = np.linspace(0, 10, num=5)
print(a)


# Xác định kiểu dữ liệu
a = np.ones(5, dtype=np.int64)
a

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0.   2.5  5.   7.5 10. ]


array([1, 1, 1, 1, 1], dtype=int64)

In [7]:
# Thêm, xóa, sắp xếp mảng

# Tạo mảng ban đầu
arr = np.array([3, 1, 2, 4, 5])
print(arr)

[3 1 2 4 5]


In [8]:
arr = np.sort(arr)
print(arr)

[1 2 3 4 5]


In [9]:
arr = np.sort(arr)[::-1]
print(arr)

[5 4 3 2 1]


In [10]:
#them phần tử
arr = np.append(arr,10)
print(arr)

[ 5  4  3  2  1 10]


In [11]:
#xóa đi vị trí nào đó trong mảng
arr = np.delete(arr,3)
print(arr)

[ 5  4  3  1 10]


In [12]:
# Tạo một mảng 2 chiều
arr = np.array([[3, 2, 1],
                [4, 6, 5],
                [9, 7, 8]])

In [13]:
tangtheohang = np.sort(arr, axis=1)
print(tangtheohang) #1 là theo hàng, 0 là theo cột

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
tangtheocot = np.sort(arr, axis=0) 
print(tangtheocot)#1 là theo hàng, 0 là theo cột

[[3 2 1]
 [4 6 5]
 [9 7 8]]


In [16]:
giamtheohang = -np.sort(-arr, axis=1)
print(giamtheohang)#1 là theo hàng, 0 là theo cột

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [18]:
giamtheocot = -np.sort(-arr, axis=0)
print(giamtheocot)#1 là theo hàng, 0 là theo cột

[[9 7 8]
 [4 6 5]
 [3 2 1]]


In [19]:
# Tạo một mảng 2D
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [20]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [22]:
so_chieu = arr.ndim  # Số chiều (2 chiều)
kich_thuoc = arr.size  # Kích thước (tổng số phần tử, 6)
hinh_dang = arr.shape  # Hình dạng (số hàng x số cột, (2, 3))

print("Sc:", so_chieu)
print("Kt:", kich_thuoc)
print("Hd:", hinh_dang)

Sc: 2
Kt: 6
Hd: (2, 3)


In [24]:
# Chuyển đổi kiểu dữ liệu
arr = np.array([1, 2, 3, 4, 5])
arr_float = arr.astype(float)
print(arr_float)

[1. 2. 3. 4. 5.]


In [26]:

# Thay đổi hình dạng của mảng
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)#2hanfg 3 cột

[[1 2 3]
 [4 5 6]]


In [28]:
reshaped_arr = arr.reshape(3,2)
print(reshaped_arr)#3 hàng 2 cột

[[1 2]
 [3 4]
 [5 6]]


In [29]:
arr = reshaped_arr.flatten() # Chuyển thành mảng 1 chiều
print(arr)

[1 2 3 4 5 6]


In [30]:

# Cắt lát mảng
arr = np.array([1, 2, 3, 4, 5,6,7,8,9])

In [31]:
sub_arr = arr[1:4]  # Cắt từ phần tử thứ 1 đến 4
print(sub_arr) # lấy vị trí 1 cho tới vị trí trước 4

[2 3 4]


In [33]:
sub_arr = arr[:-1]  
print(sub_arr)#lấy từ vị trí 0 cho đến vị trí trước(tức -2) -1(vị trí -1 = vị trí max của mảng)

[1 2 3 4 5 6 7 8]


In [34]:
sub_arr = arr[-2:] 
print(sub_arr) #vị trí -2 lùi sau -1 và 0(2 số cuối)

[8 9]


In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [37]:
transposed_arr = arr.T
print(transposed_arr) #chuyển từ 2 hàng 3 cột thành 2 cột 3 hàg

[[1 4]
 [2 5]
 [3 6]]


In [40]:
arr1 = np.array([1, 2, 3,4])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr) #gộp 2 mảng, lấy cả số trùng

[1 2 3 4 4 5 6]


In [41]:
# - Hàm numpy.sum() cho phép tính tổng các phần tử trong mảng.
arr = np.array([1, 2, 3, 4, 5])
total = np.sum(arr)
print("Tổng của mảng arr:", total)


Tổng của mảng arr: 15


In [42]:
average = np.mean(arr)
print("Giá trị trung bình của mảng arr:", average)

Giá trị trung bình của mảng arr: 3.0


In [43]:
max_value = np.max(arr)
min_value = np.min(arr)
print("Giá trị lớn nhất trong mảng arr:", max_value)
print("Giá trị nhỏ nhất trong mảng arr:", min_value)

Giá trị lớn nhất trong mảng arr: 5
Giá trị nhỏ nhất trong mảng arr: 1


In [44]:
# V. Hàm tính độ lệch chuẩn (Standard Deviation)
# - Hàm numpy.std() tính độ lệch chuẩn của mảng, đo lường mức độ phân tán của dữ liệu.
std_deviation = np.std(arr)
print("Độ lệch chuẩn của mảng arr:", std_deviation)

Độ lệch chuẩn của mảng arr: 1.4142135623730951


In [45]:
# VI. Hàm tính phương sai (Variance)
# - Hàm numpy.var() tính phương sai của mảng, đo lường mức độ biến thiên của dữ liệu.
variance = np.var(arr)
print("Phương sai của mảng arr:", variance)

Phương sai của mảng arr: 2.0


In [46]:
# VII. Hàm tính tổng tích chập (Dot Product)
# - Hàm numpy.dot() tính tổng tích chập của hai mảng (vector).
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
dot_product = np.dot(arr1, arr2)
print("Tổng tích chập của arr1 và arr2:", dot_product)

Tổng tích chập của arr1 và arr2: 32
