In [1]:
import numpy as np


In [2]:
#tạo mảng
a = np.array([1,2,3])

#in mảng 
print(a)

#in ra 1 phần tử
ele = a[1]
print(ele)

[1 2 3]
2


In [3]:
#tạo mảng 2 chiều

In [4]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("matrix: ")
print(matrix)

matrix: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#in một phần tử 
# In một phần tử
element = matrix[1, 2]
print(element)

6


In [6]:
# Cách tạo mảng
# Tạo mảng toàn là số 0
a = np.zeros(5)
print(a)

# Tạo mảng toàn là số 1
a = np.ones(5)
print(a)

# Tạo mảng
a = np.empty(5)
print(a)

# Tạo mảng từ 0 đến 100
a = np.arange(100)
print(a)

# Tạo mảng gồm các phần tử với khoảng cách đều nhau
a = np.linspace(0, 10, num=5)
print(a)


# Xác định kiểu dữ liệu
a = np.ones(5, dtype=np.int64)
a

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0.   2.5  5.   7.5 10. ]


array([1, 1, 1, 1, 1], dtype=int64)

In [7]:
# Thêm, xóa, sắp xếp mảng

# Tạo mảng ban đầu
arr = np.array([3, 1, 2, 4, 5])
print(arr)

[3 1 2 4 5]


In [8]:
arr = np.sort(arr)
print(arr)

[1 2 3 4 5]


In [9]:
arr = np.sort(arr)[::-1]
print(arr)

[5 4 3 2 1]


In [10]:
#them phần tử
arr = np.append(arr,10)
print(arr)

[ 5  4  3  2  1 10]


In [11]:
#xóa đi vị trí nào đó trong mảng
arr = np.delete(arr,3)
print(arr)

[ 5  4  3  1 10]


In [12]:
# Tạo một mảng 2 chiều
arr = np.array([[3, 2, 1],
                [4, 6, 5],
                [9, 7, 8]])

In [13]:
tangtheohang = np.sort(arr, axis=1)
print(tangtheohang) #1 là theo hàng, 0 là theo cột

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
tangtheocot = np.sort(arr, axis=0) 
print(tangtheocot)#1 là theo hàng, 0 là theo cột

[[3 2 1]
 [4 6 5]
 [9 7 8]]


In [16]:
giamtheohang = -np.sort(-arr, axis=1)
print(giamtheohang)#1 là theo hàng, 0 là theo cột

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [17]:
giamtheocot = -np.sort(-arr, axis=0)
print(giamtheocot)#1 là theo hàng, 0 là theo cột

[[9 7 8]
 [4 6 5]
 [3 2 1]]
